services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/echarts/home.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,golioth-websocket-datasource,marcusolsson-json-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-echarts-panel
      - ./provisioning:/etc/grafana/provisioning
      - ./echarts:/etc/grafana/provisioning/dashboards/echarts
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main@sha256:8fb297ea49e1e66a2e15ef1e784fee1121ce91494c85e4d96384cd9b8d9b821f
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,golioth-websocket-datasource,marcusolsson-json-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-echarts-panel
      - ./provisioning:/etc/grafana/provisioning
      - ./echarts:/etc/grafana/provisioning/dashboards/echarts
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,golioth-websocket-datasource,marcusolsson-json-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-echarts-panel
      - ./provisioning:/etc/grafana/provisioning
      - ./echarts:/etc/grafana/provisioning/dashboards/echarts
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      - grafana
    profiles:
      - playwright
